package nezet;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class Oldalbeallitas extends javax.swing.JFrame {

    public Oldalbeallitas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlPapir = new javax.swing.JPanel();
        lblMeret = new javax.swing.JLabel();
        cmdMeret = new javax.swing.JComboBox<>();
        cmdForras = new javax.swing.JComboBox<>();
        lblErtek = new javax.swing.JLabel();
        pnlElonezet = new javax.swing.JPanel();
        lblKep = new javax.swing.JLabel();
        pnlTajolas = new javax.swing.JPanel();
        rdbFekvo = new javax.swing.JRadioButton();
        rdbAllo = new javax.swing.JRadioButton();
        pnlMargok = new javax.swing.JPanel();
        lblBal = new javax.swing.JLabel();
        txtBal = new javax.swing.JTextField();
        txtFelso = new javax.swing.JTextField();
        lblFelso = new javax.swing.JLabel();
        txtJobb = new javax.swing.JTextField();
        txtAlso = new javax.swing.JTextField();
        lblJobb = new javax.swing.JLabel();
        lblAlso = new javax.swing.JLabel();
        lblFejlec = new javax.swing.JLabel();
        lblLablec = new javax.swing.JLabel();
        txtFejlec = new javax.swing.JTextField();
        txtLablec = new javax.swing.JTextField();
        lblGoogle = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnMegse = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Oldalbeállítás");
        setMaximizedBounds(new java.awt.Rectangle(250, 200, 700, 520));
        setMinimumSize(new java.awt.Dimension(320, 240));

        pnlPapir.setBorder(javax.swing.BorderFactory.createTitledBorder(null));

        lblMeret.setText("Méret:");

        cmdMeret.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Papír választás", "A3", "A4", "A5" }));
        cmdMeret.setSelectedIndex(2);

        cmdForras.setEnabled(false);

        lblErtek.setText("Forrás:");
        lblErtek.setEnabled(false);

        javax.swing.GroupLayout pnlPapirLayout = new javax.swing.GroupLayout(pnlPapir);
        pnlPapir.setLayout(pnlPapirLayout);
        pnlPapirLayout.setHorizontalGroup(
            pnlPapirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPapirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPapirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMeret)
                    .addComponent(lblErtek))
                .addGap(18, 18, 18)
                .addGroup(pnlPapirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdMeret, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmdForras, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlPapirLayout.setVerticalGroup(
            pnlPapirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPapirLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPapirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMeret)
                    .addComponent(cmdMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPapirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblErtek)
                    .addComponent(cmdForras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlElonezet.setBorder(javax.swing.BorderFactory.createTitledBorder(null));

        lblKep.setBackground(new java.awt.Color(204, 204, 204));
        lblKep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/papir.PNG"))); // NOI18N

        javax.swing.GroupLayout pnlElonezetLayout = new javax.swing.GroupLayout(pnlElonezet);
        pnlElonezet.setLayout(pnlElonezetLayout);
        pnlElonezetLayout.setHorizontalGroup(
            pnlElonezetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlElonezetLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblKep)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlElonezetLayout.setVerticalGroup(
            pnlElonezetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlElonezetLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblKep)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTajolas.setBorder(javax.swing.BorderFactory.createTitledBorder(null));

        buttonGroup1.add(rdbFekvo);
        rdbFekvo.setText("Fekvő");
        rdbFekvo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbFekvoItemStateChanged(evt);
            }
        });

        buttonGroup1.add(rdbAllo);
        rdbAllo.setMnemonic('A');
        rdbAllo.setSelected(true);
        rdbAllo.setText("Álló");
        rdbAllo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rdbAlloItemStateChanged(evt);
            }
        });
        rdbAllo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAlloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTajolasLayout = new javax.swing.GroupLayout(pnlTajolas);
        pnlTajolas.setLayout(pnlTajolasLayout);
        pnlTajolasLayout.setHorizontalGroup(
            pnlTajolasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTajolasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTajolasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbFekvo)
                    .addComponent(rdbAllo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTajolasLayout.setVerticalGroup(
            pnlTajolasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTajolasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdbAllo)
                .addGap(18, 18, 18)
                .addComponent(rdbFekvo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlMargok.setBorder(javax.swing.BorderFactory.createTitledBorder(null));

        lblBal.setText("Bal:");

        txtBal.setText("20");

        txtFelso.setText("25");

        lblFelso.setText("Felső");

        txtJobb.setText("jobb");

        txtAlso.setText("25");

        lblJobb.setText("Jobb");

        lblAlso.setText("Alsó");

        javax.swing.GroupLayout pnlMargokLayout = new javax.swing.GroupLayout(pnlMargok);
        pnlMargok.setLayout(pnlMargokLayout);
        pnlMargokLayout.setHorizontalGroup(
            pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMargokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBal)
                    .addComponent(lblFelso))
                .addGap(18, 18, 18)
                .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFelso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJobb)
                    .addComponent(lblAlso))
                .addGap(18, 18, 18)
                .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtJobb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAlso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMargokLayout.setVerticalGroup(
            pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMargokLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMargokLayout.createSequentialGroup()
                        .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblJobb)
                            .addComponent(txtJobb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAlso)
                            .addComponent(txtAlso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMargokLayout.createSequentialGroup()
                        .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBal)
                            .addComponent(txtBal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMargokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFelso)
                            .addComponent(txtFelso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblFejlec.setText("Fejléc:");

        lblLablec.setText("Lábléc:");

        lblGoogle.setText("<html><a href=\"#\">Értékek megadása</a></html>");
        lblGoogle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGoogle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGoogleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGoogleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGoogleMouseExited(evt);
            }
        });

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnMegse.setText("Mégse");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFejlec)
                            .addComponent(lblLablec))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtFejlec)
                            .addComponent(txtLablec)))
                    .addComponent(pnlPapir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnlTajolas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlMargok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                        .addComponent(btnMegse, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addComponent(pnlElonezet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMegse, btnOk});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlPapir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnlTajolas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlMargok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFejlec)
                            .addComponent(txtFejlec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLablec)
                            .addComponent(txtLablec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnlElonezet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnMegse)
                    .addComponent(lblGoogle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        //Object szoveg = cmdMeret.getSelectedItem().toString();
        String szoveg = (String) cmdMeret.getSelectedItem();
        int index = cmdMeret.getSelectedIndex();
        
        //System.out.printf("papír: %s, [%d]", szoveg, index);
        if(index > 0){
            System.exit(0);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Nincs papír kiválasztva");
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void lblGoogleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoogleMouseClicked
        try {
            //Desktop.getDesktop().browse(new URI("http://google.com"));
            Desktop.getDesktop().browse(URI.create("http://google.com"));
        } catch (IOException ex) {
            Logger.getLogger(Oldalbeallitas.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lblGoogleMouseClicked

    private void lblGoogleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoogleMouseEntered
        lblGoogle.setText("<html><a href=\"#\"><b>Google böngészőben</b></a></html>");
    }//GEN-LAST:event_lblGoogleMouseEntered

    private void lblGoogleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoogleMouseExited
        lblGoogle.setText("<html><a href=\"#\">Értékek megadása</a></html>");
    }//GEN-LAST:event_lblGoogleMouseExited

    /* kattintás nem jó, mert akkor is megcsinálja, 
    ha nincs változás a kijelölésben
    */
    private void rdbAlloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAlloActionPerformed
        //csere();
    }//GEN-LAST:event_rdbAlloActionPerformed
	
    /* a másik gombra nem kell, mert akkor oda-vissza cserélnek */
    private void rdbAlloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbAlloItemStateChanged
        csere();
        lblKep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/papir.PNG")));
    }//GEN-LAST:event_rdbAlloItemStateChanged

    private void rdbFekvoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rdbFekvoItemStateChanged
        /* itt nem kell meghívni, mert csak visszacserélne! */
        //csere();
        lblKep.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kepek/papirFekvo.PNG")));
    }//GEN-LAST:event_rdbFekvoItemStateChanged

    
    private void csere(){
        String felso, also, jobb, bal;
        jobb = txtJobb.getText();
        bal = txtBal.getText();
        also = txtAlso.getText();
        felso = txtFelso.getText();
        
        txtBal.setText(felso);
        txtFelso.setText(bal);
        
        txtJobb.setText(also);
        txtAlso.setText(jobb);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oldalbeallitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oldalbeallitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oldalbeallitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oldalbeallitas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oldalbeallitas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegse;
    private javax.swing.JButton btnOk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmdForras;
    private javax.swing.JComboBox<String> cmdMeret;
    private javax.swing.JLabel lblAlso;
    private javax.swing.JLabel lblBal;
    private javax.swing.JLabel lblErtek;
    private javax.swing.JLabel lblFejlec;
    private javax.swing.JLabel lblFelso;
    private javax.swing.JLabel lblGoogle;
    private javax.swing.JLabel lblJobb;
    private javax.swing.JLabel lblKep;
    private javax.swing.JLabel lblLablec;
    private javax.swing.JLabel lblMeret;
    private javax.swing.JPanel pnlElonezet;
    private javax.swing.JPanel pnlMargok;
    private javax.swing.JPanel pnlPapir;
    private javax.swing.JPanel pnlTajolas;
    private javax.swing.JRadioButton rdbAllo;
    private javax.swing.JRadioButton rdbFekvo;
    private javax.swing.JTextField txtAlso;
    private javax.swing.JTextField txtBal;
    private javax.swing.JTextField txtFejlec;
    private javax.swing.JTextField txtFelso;
    private javax.swing.JTextField txtJobb;
    private javax.swing.JTextField txtLablec;
    // End of variables declaration//GEN-END:variables

}
