/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author OlajosViola(SZF_E_20
 */
public class Szamolas extends javax.swing.JFrame {

    /**
     * Creates new form Szamolas
     */
    private int fiz;
    private String s;
    public Szamolas() {
        initComponents();
        fiz=0;
        s="Választott feltét:\n";
    }
    
    private void fizKalk(JCheckBox gomb){
        if(gomb.isSelected()==true){fiz+=200;}else{fiz+=-200;}
        lblFiz.setText("Fizetendő: "+fiz+" Ft");
    }
    
    private String rendelTxt(JCheckBox gomb, String feltet){
        if(gomb.isSelected()==true){s+=feltet+"\n";}
        return s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        feltetek = new javax.swing.JPanel();
        checkSajt = new javax.swing.JCheckBox();
        checkAnanasz = new javax.swing.JCheckBox();
        checkHagyma = new javax.swing.JCheckBox();
        lblFiz = new javax.swing.JLabel();
        rendelButton = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rendelés");
        setResizable(false);

        feltetek.setBorder(javax.swing.BorderFactory.createTitledBorder("Feltétek"));
        feltetek.setToolTipText("");

        checkSajt.setText("sajt");
        checkSajt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkSajtItemStateChanged(evt);
            }
        });

        checkAnanasz.setText("ananász");
        checkAnanasz.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkAnanaszItemStateChanged(evt);
            }
        });

        checkHagyma.setText("hagyma");
        checkHagyma.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkHagymaItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout feltetekLayout = new javax.swing.GroupLayout(feltetek);
        feltetek.setLayout(feltetekLayout);
        feltetekLayout.setHorizontalGroup(
            feltetekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feltetekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(feltetekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkHagyma)
                    .addComponent(checkSajt)
                    .addComponent(checkAnanasz))
                .addContainerGap())
        );
        feltetekLayout.setVerticalGroup(
            feltetekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(feltetekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checkHagyma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkSajt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkAnanasz)
                .addContainerGap())
        );

        checkSajt.getAccessibleContext().setAccessibleName("checkSajt");
        checkAnanasz.getAccessibleContext().setAccessibleName("checkAnanasz");
        checkHagyma.getAccessibleContext().setAccessibleName("checkHagyma");

        lblFiz.setText("Fizetendő: 0 Ft");

        rendelButton.setText("Megrendelem");
        rendelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rendelButtonMouseClicked(evt);
            }
        });
        rendelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rendelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblFiz)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(feltetek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(rendelButton)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(feltetek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rendelButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFiz)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        feltetek.getAccessibleContext().setAccessibleName("Feltétek");
        lblFiz.getAccessibleContext().setAccessibleName("lblFiz");
        rendelButton.getAccessibleContext().setAccessibleName("rendelButton");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rendelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rendelButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_rendelButtonActionPerformed

    private void checkHagymaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkHagymaItemStateChanged
        // TODO add your handling code here:
        fizKalk(checkHagyma);
    }//GEN-LAST:event_checkHagymaItemStateChanged

    private void checkSajtItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkSajtItemStateChanged
        // TODO add your handling code here:
        fizKalk(checkSajt);
    }//GEN-LAST:event_checkSajtItemStateChanged

    private void checkAnanaszItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkAnanaszItemStateChanged
        // TODO add your handling code here:
        fizKalk(checkAnanasz);
    }//GEN-LAST:event_checkAnanaszItemStateChanged

    private void rendelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rendelButtonMouseClicked
        // TODO add your handling code here:
        rendelTxt(checkHagyma, "hagyma");
        rendelTxt(checkSajt, "sajt");
        rendelTxt(checkAnanasz, "ananász");
        if(s=="Választott feltét:\n"){
            JOptionPane.showMessageDialog(rootPane, "Nem választottál feltétet!");
        }else{
            JOptionPane.showMessageDialog(rootPane, s);
        }
        s="Választott feltét:\n";
    }//GEN-LAST:event_rendelButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Szamolas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Szamolas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Szamolas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Szamolas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Szamolas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkAnanasz;
    private javax.swing.JCheckBox checkHagyma;
    private javax.swing.JCheckBox checkSajt;
    private javax.swing.JPanel feltetek;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JLabel lblFiz;
    private javax.swing.JButton rendelButton;
    // End of variables declaration//GEN-END:variables
}
